export const ptContent = {
  meta: {
    title: "Star Wok | Restaurante Buffet",
    description: "Conheça o Star Wok, um restaurante buffet em São Domingos de Rana com um espaço amplo e uma experiência inspirada no universo.",
  },
  navigation: {
    label: "Navegação principal",
    home: "Início",
    buffet: "Buffet",
    space: "O Nosso Espaço",
    information: "Informações",
    reserve: "Reservar",
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    portuguese: "Português",
    english: "English",
    changeLanguage: "Mudar idioma",
  },
  hero: {
    reserve: "Reservar mesa",
    logoAlt: "Star Wok",
    imageAlt: "Interior amplo do Star Wok com planetas iluminados, teto estrelado e detalhes em cobre",
  },
  reservation: {
    title: "Reservar mesa",
    back: "Voltar ao Star Wok",
    iframeTitle: "Formulário de reserva Star Wok",
    description: "Reserve a sua mesa no Star Wok.",
  },
  buffet: {
    title: "O Nosso Buffet",
    prices: "Preços",
    adults: "Adultos",
    children: "Crianças",
    childFree: "Até aos 3 anos: grátis.",
    childPricing: "Dos 4 anos até 1,30 m: 8,50 € ao almoço de segunda a sexta; 9,50 € nos restantes períodos.",
    dineInExclusions: "* Bebidas e café não incluídos.",
    dineIn: "No restaurante",
    takeaway: "Take-Away",
    perBox: "Por caixa",
    pricingType: "Tipo de preço",
    takeawayPackagingNote: "Informamos que, devido à Portaria n.º 331-E/2021, a partir de 31 de dezembro de 2024, as caixas de take-away têm um custo adicional de 0,30 € por unidade.",
    carouselLabel: "Fotografias do buffet",
    previous: "Fotografia anterior",
    next: "Fotografia seguinte",
    choosePhoto: "Escolher fotografia do buffet",
    viewPhoto: "Ver fotografia",
  },
  space: {
    title: "O Nosso Espaço",
    galleryLabel: "Fotografias do espaço Star Wok",
  },
  information: {
    title: "Informações",
    address: "Morada",
    phone: "Telefone",
    email: "Email",
    openingHours: "Horário",
    everyDay: "Todos os dias",
    services: "Serviços",
    accessibility: "Acessibilidade",
    parking: "Estacionamento",
    paymentOptions: "Pagamentos",
    reserve: "Reservar mesa",
    externalLink: "abre numa nova janela",
    mapTitle: "Localização do Star Wok no Google Maps",
  },
  footer: {
    navigationLabel: "Navegação no rodapé",
    informationTitle: "Informações",
    navigationTitle: "Navegação",
    legalTitle: "Legal",
    openDaily: "Aberto todos os dias",
    designedBy: "Designed by Intelis",
    socialLabel: "Redes sociais",
    privacyPolicy: "Política de Privacidade",
    complaintsBook: "Livro de Reclamações",
    rights: "Todos os direitos reservados.",
    instagram: "Star Wok no Instagram",
    facebook: "Star Wok no Facebook",
    tiktok: "Star Wok no TikTok",
  },
} as const;

export const enContent = {
  meta: {
    title: "Star Wok | Buffet Restaurant",
    description: "Discover Star Wok, a buffet restaurant in São Domingos de Rana with a spacious interior and an experience inspired by the universe.",
  },
  navigation: {
    label: "Main navigation",
    home: "Home",
    buffet: "Buffet",
    space: "Our Space",
    information: "Information",
    reserve: "Book",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    portuguese: "Português",
    english: "English",
    changeLanguage: "Change language",
  },
  hero: {
    reserve: "Book a table",
    logoAlt: "Star Wok",
    imageAlt: "Spacious Star Wok interior with illuminated planets, a starry ceiling and copper details",
  },
  reservation: {
    title: "Book a table",
    back: "Back to Star Wok",
    iframeTitle: "Star Wok reservation form",
    description: "Book your table at Star Wok.",
  },
  buffet: {
    title: "Our Buffet",
    prices: "Prices",
    adults: "Adults",
    children: "Children",
    childFree: "Up to 3 years old: free.",
    childPricing: "From age 4 up to 1.30 m: €8.50 at weekday lunch; €9.50 at all other times.",
    dineInExclusions: "* Drinks and coffee not included.",
    dineIn: "Dine-in",
    takeaway: "Takeaway",
    perBox: "Per box",
    pricingType: "Pricing type",
    takeawayPackagingNote: "Under Ordinance no. 331-E/2021, from 31 December 2024 takeaway boxes have an additional charge of €0.30 per unit.",
    carouselLabel: "Buffet photographs",
    previous: "Previous photograph",
    next: "Next photograph",
    choosePhoto: "Choose a buffet photograph",
    viewPhoto: "View photograph",
  },
  space: {
    title: "Our Space",
    galleryLabel: "Photographs of the Star Wok restaurant",
  },
  information: {
    title: "Information",
    address: "Address",
    phone: "Phone",
    email: "Email",
    openingHours: "Opening hours",
    everyDay: "Every day",
    services: "Services",
    accessibility: "Accessibility",
    parking: "Parking",
    paymentOptions: "Payments",
    reserve: "Book a table",
    externalLink: "opens in a new window",
    mapTitle: "Star Wok location on Google Maps",
  },
  footer: {
    navigationLabel: "Footer navigation",
    informationTitle: "Information",
    navigationTitle: "Navigation",
    legalTitle: "Legal",
    openDaily: "Open every day",
    designedBy: "Designed by Intelis",
    socialLabel: "Social media",
    privacyPolicy: "Privacy Policy",
    complaintsBook: "Complaints Book",
    rights: "All rights reserved.",
    instagram: "Star Wok on Instagram",
    facebook: "Star Wok on Facebook",
    tiktok: "Star Wok on TikTok",
  },
} as const;

export const contentByLocale = {
  pt: ptContent,
  en: enContent,
} as const;

export type Locale = keyof typeof contentByLocale;
export type StarWokContent = (typeof contentByLocale)[Locale];
